version: '3'

services:
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    networks:
      - app-tier 

  grpcserver:
    container_name: grpcserver
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - "db"
    networks:
      - app-tier

  grpcclient:
    container_name: grpcclient
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - "grpcserver"
      - "db"
    networks:
      - app-tier 

networks:
  app-tier:
    driver: bridge
