version: '3'

services:
  db:
    image: postgres
    ports:
      - "5438:5432"
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    networks:
      - app-tier 

  grpcserver:
    container_name: grpcserver
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 50051:50051
    environment:
      GRPC_SERVER_HOST: grpcserver
      GRPC_SERVER_PORT: 50051
    depends_on:
      - "db"
    networks:
      - app-tier

  grpcclient:
    container_name: grpcclient
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 50050:50050
    environment:
      GRPC_SERVER_HOST: grpcserver
      GRPC_SERVER_PORT: 50051
      GRPC_CLIENT_HOST: grpcclient
      GRPC_CLIENT_PORT: 50050
    depends_on:
      - "grpcserver"
      - "db"
    networks:
      - app-tier 

networks:
  app-tier:
    driver: bridge
