version: '3'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  grpcserver:
    container_name: grpcserver
    build:
      context: .
      dockerfile: dockerfile.server
    depends_on:
      - database
    ports:
      - "50051:50051"

  grpcclient:
    container_name: grpcclient
    build:
      context: .
      dockerfile: dockerfile.client
    depends_on:
      - grpcserver
      - database
    ports:
      - "50050:50050"

volumes:  
  pgdata: {}
