FROM golang:1.20.2-alpine3.17

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY proto proto
COPY server server

# RUN go test ./server/...
RUN go build -o /app/bin/server ./server

EXPOSE 50051

ENTRYPOINT ["/app/bin/server"]